
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Building the code..."
      - run: npm install

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running tests..."
      - run: npm test

  docker-build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-dockerhub-username/circleci-image:latest .
            docker tag your-dockerhub-username/circleci-image:latest your-dockerhub-username/circleci-image:v1

  docker-push:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push your-dockerhub-username/circleci-image:latest
            docker push your-dockerhub-username/circleci-image:v1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
      - docker-build:
          requires:
            - build
            - test
      - docker-push:
          requires:
            - docker-build
